### PR TITLE
fix gitlet: improve check in files.read

### PR DESCRIPTION
**Pull request by coderaiser**
When `config` is exist and it is not file, error occurs:
```
Error: EISDIR, illegal operation on a directory
```

### CODE REVIEW

**Comment by maryrosecook** [comment]
Thanks a lot for this.  Would you mind adding a test for the case that caused you to find the bug.  Thanks very much!

**Comment by coderaiser** [comment]
Tests has a [lot fails now](https://github.com/maryrosecook/gitlet/issues/14). I think they should be fixed first.

**Comment by maryrosecook** [comment]
Would you mind running the tests on a clean master branch? If you still get fails, would you mind sending me the stack traces of some of the fails? Thanks a lot.

**Comment by maryrosecook** [comment]
Thanks a lot for the test and the fix.  I slightly changed your fix to check that config specifically is a file, rather than any file that is read by `file.read()`.  All the tests pass on my machine.  Would you mind pulling master and running them on your machine? Thanks so much for your help.

**Comment by coderaiser** [comment]
Every thing is great.
```
Finished in 37.027 seconds
286 tests, 788 assertions, 0 failures, 0 skipped
```

**Comment by maryrosecook** [comment]
Great thanks a lot!

--
http://maryrosecook.com

**Pull request closed without merging**
